apiVersion: v1
kind: Service
metadata:
    name: hanabi-net-ui
    namespace: dja3
    labels:
        run: hanabi-net
        tier: hanabi-net-ui
spec:
    type: ClusterIP
    ports:
    - protocol: TCP
      targetPort: 3000
      port: 80
    selector:
        run: hanabi-net
        tier: hanabi-net-ui
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: hanabinet-ingress
spec:
    rules:
    - host: www.hanabinet.com
      http:
        paths:
        - backend:
            serviceName: hanabi-net-ui
            servicePort: 80
    tls:
    - hosts:
      - www.hanabinet.com
      secretName: testsecret-tls
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: hanabi-net-ui
    namespace: dja3
spec:
    selector:
        matchLabels:
            run: hanabi-net
            tier: hanabi-net-ui
    replicas: 1
    template:
        metadata:
            labels:
                run: hanabi-net
                tier: hanabi-net-ui
        spec:
            containers: 
            - name: hanabi-net-ui
              image: davidadams3/hanabi-net:latest
              imagePullPolicy: Always
              env:
                  - name: PORT
                    value: "3000"
              ports:
              - containerPort: 3000

